devgeniem/tms-theme-taidemuseo

- CHANGELOG.MD
- assets/styles/ui-components/_share-links.scss
- assets/styles/ui-components/index.scss
- partials/single.dust
- partials/ui/share-links.dust
CR: TMS-628
Share links styles so that they work with single artist also
TMS-468
Local, stage
> TMS-468: Share links

- lib/ThemeCustomizationController.php
- partials/blocks/block-material.dust
CR: TMS-628
Block materials
TMS-437
> TMS-437: Block materials

- assets/styles/views/_contacts.scss
- assets/styles/views/index.scss
CR: TMS-628
Page contacts
TMS-438
> TMS-438: Add page contacts styles

- CHANGELOG.MD
- partials/views/single/single-related.dust
CR: TMS-628
Related contents styling
TMS-467
Local, stage
> TMS-467: Related contents styling

- CHANGELOG.MD
- assets/styles/layouts/_notice-banner.scss
- partials/blocks/block-notice-banner.dust
CR: TMS-628
Notice banner styling
TMS-472
Local, stage
> TMS-472: Notice banner styles

- CHANGELOG.MD
- partials/layouts/layout-icon-links.dust
CR: TMS-628
Icon links styling with classes
TMS-724
Local, stage
> TMS-724: Icon links

- CHANGELOG.MD
- partials/layouts/layout-articles-inner.dust
- partials/views/home/home-grid-item.dust
- partials/views/home/home-highlight.dust
CR: TMS-628
Removed categories, image as a link.
TMS-451
Local, staging
> TMS-451: Article highlights

- CHANGELOG.MD
- assets/styles/layouts/_call-to-action.scss
- assets/styles/utils/_rounded-image.scss
- assets/styles/utils/index.scss
- lib/ACF/AlterCallToActionLayout.php
- lib/ACF/LayoutInfoBadge.php
- partials/layouts/layout-call-to-action.dust
CR: TMS-628
- Column size selection
- Option for round image
- Image col contains image
TMS-446
Local, stage
> TMS-446: Call to action layout

- CHANGELOG.MD
- partials/views/home/home-grid-item.dust
CR: TMS-628
Bugfix for blog article grid item's category
- Fixes showing wrong category or no category at all for blog article grid items.
- TMS-475 
Local
> TMS-475: Bugfix for blog article grid item's category

- CHANGELOG.MD
- assets/styles/ui-components/_share-links.scss
CR: TMS-628
Share links slightly bigger
TMS-754
Local
> TMS-754: Share links bigger

- CHANGELOG.MD
- models/single-artwork.php
- partials/views/home/home-filters.dust
> TMS-728: Fix media gallery texts of featured image in artwork.

- CHANGELOG.MD
- partials/home.dust
CR: TMS-628
Do not display "No results found" when Home view has a featured post.
TMS-805
> TMS-805: Fix no results text logic

- CHANGELOG.MD
- models/single-artwork.php
- partials/single-artwork.dust
CR: TMS-628
Display image meta on artwork view
TMS-816
> TMS-816: Display image meta on artwork view

- CHANGELOG.MD
- lib/PostType/Artist.php
- lib/PostType/Artwork.php
CR: TMS-628
Translate CPT names
TMS-813
> TMS-813: Translate CPT names

- CHANGELOG.MD
- assets/styles/ui-components/header/_header-top.scss
- assets/styles/ui-components/header/_primary-nav.scss
CR: TMS-628
Align header logo with main navigation.
TMS-788
Stage, local.
> TMS-788: Header logo alignment

- CHANGELOG.MD
- lib/Formatters/AccordionImageFormatter.php
- partials/layouts/layout-accordion-image.dust
CR: TMS-628
Add full image meta data for images inside accordion
TMS-796
Stage, local.
> TMS-796: Image meta data for accordion images

- CHANGELOG.MD
- partials/single.dust
- partials/views/single/single-meta.dust
> TMS-224: add api image to single article template

- CHANGELOG.MD
- assets/styles/layouts/_image-carousel.scss
- assets/styles/ui-components/_modal.scss
> TMS-793: Fix modal button position

- CHANGELOG.MD
- assets/styles/views/_single-artist.scss
- partials/single-artist.dust
> TMS-848: Resize single artist image and adjust position

- CHANGELOG.MD
- partials/page-event.dust
> TMS-795: Change event image credit position

- CHANGELOG.MD
- partials/views/home/home-grid-item.dust
CR: TMS-628
Show drupal image on home result card
TMS-862
Show drupal image on home result card
> TMS-862: Show drupal image on home result card

- CHANGELOG.MD
- models/archive-exhibition.php
CR: TMS-628
Fix issue with date filters when end_date is today
TMS-869
> TMS-869: Fix issue with date filters when end_date is today

- CHANGELOG.MD
- assets/styles/ui-components/_additional-info.scss
CR: TMS-628
Fix artist table alignment
[TMS-853](https://geniemdev.atlassian.net/browse/TMS-853)
> TMS-853: Fix artist table alignment

- CHANGELOG.MD
- assets/styles/theme-taidemuseo.scss
> TMS-871: prevent vertical images from cropping

- CHANGELOG.MD
- assets/styles/blocks/_accordion.scss
- assets/styles/blocks/_image.scss
- assets/styles/settings/_settings.scss
- assets/styles/views/_single-artist.scss
- assets/styles/views/_single.scss
- partials/layouts/layout-accordion-image.dust
- partials/layouts/layout-content-columns.dust
- partials/shared/artwork-list.dust
- partials/single-artist.dust
- partials/single-artwork.dust
- partials/single.dust
> TMS-818: Fix images

- models/archive-exhibition.php
Task: TMS-913
Fix upcoming exhibitions page not opening
> Fix upcoming exhibition page not opening

- CHANGELOG.MD
- partials/views/single/single-related.dust
CR: PIEN-8524
Display API images in related articles
PIEN-8524
> PIEN-8524: Display API images

- CHANGELOG.MD
- partials/layouts/layout-image-carousel.dust
Task: https://hiondigital.atlassian.net/browse/TMS-936
Image carousel layout accessibility fixes
> TMS-936: Image carousel accessibility fixes

- CHANGELOG.MD
- models/archive-exhibition.php
Task: https://hiondigital.atlassian.net/browse/TMS-982
Fix exhibition-archive year-filters & search
> TMS-982: Fix exhibition-archive year-filters & search

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.MD
- assets/styles/ui-components/_archive-filters.scss
- partials/views/home/home-filters.dust
- style.css
Severa-ID: 2108
Severa-kuvaus: TMS-935 TMS - Saavutettavuus: Onnistumistarinat
Task: https://hiondigital.atlassian.net/browse/TMS-935
- Add info-text to filters about page refreshing after selection
- Add aria-attributes and nav-landmark to partial
> TMS-935: Archive filter accessibility fixes

- CHANGELOG.MD
- assets/styles/layouts/_image-carousel.scss
- style.css
Severa-ID: 2247
Severa-kuvaus: TMS-1021 Kuvakarusellin vaakakuvien asemointi
Task: https://hiondigital.atlassian.net/browse/TMS-1021
Remove max-height to prevent modal alignment problems with tms-theme-base fix
> TMS-1021: Remove image carousel modal max-height

- CHANGELOG.MD
- partials/views/page-events-calendar/page-events-calendar-item-grid.dust
Severa-ID: 2247
Severa-kuvaus: TMS-1071 Lihavointi pois taidemuseon Maksuton-ilmauksesta
Task: https://hiondigital.atlassian.net/browse/TMS-1071
Fix price elements class in event-listing
> TMS-1071: Fix events price element class

- CHANGELOG.MD
- lib/ACFController.php
- lib/FormatterController.php
- lib/PostType/Artwork.php
- lib/PostTypeController.php
- lib/ThemeController.php
- lib/autoload.php
- models/single-exhibition.php
Severa-ID: 2108
Severa-kuvaus: TMS-1075 Redipress 2 päivitys
Task: https://hiondigital.atlassian.net/browse/TMS-1075
Filter changes for Redipress 2 update
> TMS-1075: Redipress 2 filters

- CHANGELOG.MD
- assets/styles/blocks/_table.scss
- assets/styles/layouts/_image-carousel.scss
- assets/styles/settings/brand/_typography.scss
- assets/styles/ui-components/_button.scss
- assets/styles/ui-components/_forms.scss
- assets/styles/ui-components/_image-gallery.scss
- assets/styles/ui-components/_modal.scss
- assets/styles/ui-components/header/_header-top.scss
- assets/styles/ui-components/header/_language-nav.scss
- assets/styles/ui-components/header/_site-header-notice.scss
Severa-ID: 2247
Severa-kuvaus: TMS-1160 Saavutettavuus: Vapriikin kohdistuksia puuttuu + muutoksia niihin
Task: https://hiondigital.atlassian.net/browse/TMS-1160
Improve focus outlines for elements to improve accessibility
> TMS-1160: Fix elements focus outline thickness

- CHANGELOG.MD
- partials/blocks/block-video.dust
Projekti: Tampereen kaupunki, konsernihallinto / Tietohallintoyksikkö: Tampere multisite support
Tiketin kuvaus: TMS-1201 Uusi Quickchannel-alusta sallituksi videolohkoon ja -komponenttiin
Task: https://hiondigital.atlassian.net/browse/TMS-1201
Add new field for video-component that enables an iframe-video to be embedded.
> TMS-1201: Add iframe-field for video fields
